version = 0.1
[default.deploy.parameters]
stack_name = "space-desert"
resolve_s3 = true
s3_prefix = "space-desert"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "MountDataLayer=\"true\""
