AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Space Desert

Globals:
  Function:
    Timeout: 90

Parameters:
  MountDataLayer:
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    Description: Mount the data layer to the function

Conditions:
  ShouldMountDataLayer: !Equals [ !Ref MountDataLayer, true ]

Resources:
  CalculateScoreFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: ..
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [arm64]
      MemorySize: 128
      Tracing: Active
      Environment:
        Variables:
          HasDataLayer: !Ref MountDataLayer
      Layers:
        !If [ShouldMountDataLayer, [!Ref DataLayer], !Ref AWS::NoValue]

  DataLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
        LayerName: sam-data-layer
        Description: Data for [calculate-score]
        ContentUri: ../data/
        LicenseInfo: 'MIT'
        RetentionPolicy: Delete

Outputs:
  CalculateScoreFunction:
    Description: "CalculateScoreFunction ARN"
    Value: !GetAtt CalculateScoreFunction.Arn
  CalculateScoreFunctionIamRole:
    Description: "Implicit IAM Role created for CalculateScoreFunction"
    Value: !GetAtt CalculateScoreFunctionRole.Arn

